# Generated by Django 4.2.24 on 2025-09-17 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_about_eatured_image_alter_about_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='eatured_image',
            new_name='featured_image',
        ),
    ]
